arch: "poundnet"
test_name: "Poundnet_1"

eval_pipeline: utils.validate_poundnet
resume:
  path: './weights/poundnet_ViTL_Progan_20240506_23_30_25.ckpt'
  target: utils.resume_tools.resume_lightning

model:
  NAME: "ViT-L/14"
  N_CTX_VISION: 16
  N_CTX_TEXT: 16
  CTX_INIT: False
  PROMPT_DEPTH_VISION: 8
  PROMPT_DEPTH_TEXT: 8
  PROMPT_NUM_TEXT: 1


datasets:
  train:
    multicalss_names: ["airplane", "bird", "bottle", "car", "chair", "diningtable", "horse", "person", "sheep", "train",
                       "bicycle", "boat", "bus", "cat", "cow", "dog", "motorbike", "pottedplant", "sofa", "tvmonitor"]

  base_path: "/home/data/yabin/DF-arrow"
  source:

    - { target: data.ArrowDatasets,
        data_root: '${datasets.base_path}/ForenSynths',
        sub_sets: [  "progan" ],
        split: 'test',
        benchmark_name: 'ForenSynths' }

        
  batch_size: 64
  loader_workers: 32

  trsf:
    - _target_: torchvision.transforms.Resize
      size: 256
    - _target_: torchvision.transforms.CenterCrop
      size: 224
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean: [0.48145466, 0.4578275, 0.40821073]
      std: [0.26862954, 0.26130258, 0.27577711]
